DROP PROCEDURE IF EXISTS add_proc; 

DELIMITER $$

CREATE PROCEDURE add_proc(@word AS VARCHAR(255) NOT NULL)
AS 
BEGIN
    CREATE TABLE IF NOT EXISTS clues (id INTEGER PRIMARY KEY, word VARCHAR(255) NOT NULL)
    INSERT INTO clues VALUES(NULL, @word)
END;